print("caseStudy: 알고리즘3-20부터 0까지 짝수를 출력")
print("03_ex03_evenPrint_003.py")
print("forloopTest2")
print()
print("1. n, i 변수 선언과 초기화")
print('   n = 20 ')
n = 20
print()
print("2. 반복 실행하는 반복문: ")
print('   for i in range(20,-1,-2):  ')
print('       print(n, end=" ")  ')
print('       n = n - 2  ')
print()
print("3. 결과값->")
for i in range(20,-1,-2):
    print(n, end=" ")
    n = n - 2
print()
print()
print('4. 프로그램 종료')
print('   print("Program End")')
print("   Program End")