print("caseStudy: 입력된 값 반환")
print("m3_2_whileLoopTest_002.py")
print()
print("1. value 변수 선언과 초기화")
print('   value = 1    ')
value = 1
print()
print("2. While 반복문")
print('   while value <= 100:                   ')
print('       value = int(input("숫자 입력 :")) ')
print('       print("입력된 값 :", value)       ')
print()
print("3. 결과값->")
while value <= 100:
    value = int(input("숫자 입력 :"))
    print("입력된 값 :", value)
print()
print('4. 프로그램 종료')
print('   print("Program End")')
print("   Program End")