print("caseStudy: GugudanType3")
print("m3_2_nestedloop_002_GugudanType3")
print()
print("1. Variable Declaration and initialization: 변수 선언과 초기화")
print('   i, j = 0, 0 ')
i, j = 0, 0
print()
print("2. Nested Loop: 중첩 반복문")
print("   for i in range(2, 10, 1) : ")
print("       for j in range(1, 10, 1) : ")
print('           print(" %d x %d = %2d" % (i, j, i*j), end="\\t") ')
print('       print("") ')
print()
print("3. Result: 결과값->")
for i in range(2, 10, 1) :
    for j in range(1, 10, 1) :
        print(" %d x %d = %2d" % (i, j, i*j), end="\t")
    print("")
print()
print('4. Program end: 프로그램 종료')
print('   print("Program End")')
print("   Program End")