print("caseStudy: 반복문-20부터 0까지 나열")
print('m3_2_forloopTest_001_02.py\n')
print("1. i 변수 선언")
print()
print("2. 반복 실행하는 반복문 ")
print('   for i in range(20, -1, -1):  ')
print("           print(i, end=' ')    ")
print()
print("3. 결과값->")
for i in range(20, -1, -1):
        print(i, end=' ')
print()
print('4. 프로그램 종료')
print('   print("Program End")')
print("   Program End")